# Generated by Django 4.0.2 on 2022-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_snippet_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='link',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
