# Generated by Django 4.0.2 on 2022-02-18 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_snippet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='link',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
